USE moneymanager
CREATE TABLE EXAMP (CATEGORY_ID VARCHAR(20) PRIMARY KEY)
INSERT INTO EXAMP VALUES  ('C1');
INSERT INTO EXAMP VALUES  ('C2');
INSERT INTO EXAMP VALUES  ('C3');
SELECT*FROM EXAMP

CREATE TABLE TRANSACT_TABLE( TRANSAC_ID VARCHAR(10) PRIMARY KEY,TRANSAC_NAME VARCHAR(20) NOT NULL, AMOUNT INT NOT NULL,CATEGORY_ID VARCHAR(20) NOT NULL,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME,
    FOREIGN KEY(CATEGORY_ID) REFERENCES EXAMP(CATEGORY_ID))

INSERT INTO TRANSACT_TABLE VALUES  ('T1','INCOME',4789, 'C1',GETDATE(),GETDATE());
SELECT*FROM TRANSACT_TABLE

ALTER PROCEDURE TRANSAC 	             (@TRASAC_ID            VARCHAR(10),
                                          @TRASAC_NAME    VARCHAR(20),
                                          @AMOUNT     INT,
                                          @CATERGORY_ID        VARCHAR(20),
                                          @CREATED_DATE          DATETIME=NULL,
										  @MODIFIED_DATE         DATETIME=NULL)
WITH ENCRYPTION

AS
SET @CREATED_DATE =COALESCE(@CREATED_DATE,GETDATE())
SET @MODIFIED_DATE =COALESCE(@MODIFIED_DATE,GETDATE())
BEGIN
		   INSERT INTO TRANSACT_TABLE(TRANSAC_ID,TRANSAC_NAME, AMOUNT,CATEGORY_ID,CREATED_DATE,MODIFIED_DATE)
		   VALUES(@TRASAC_ID,@TRASAC_NAME,@AMOUNT,@CATERGORY_ID,@CREATED_DATE,@MODIFIED_DATE)
 END

 EXEC TRANSAC   'T2','DEBIT',4000,'C2'

 ALTER PROCEDURE TRANSAC 	            
WITH ENCRYPTION

AS
BEGIN
		   SELECT*FROM TRANSACT_TABLE
 END

 EXEC TRANSAC

 ALTER PROCEDURE TRANSAC(@TRANSAC_ID VARCHAR(20)) 	            
WITH ENCRYPTION

AS
BEGIN
		   SELECT*FROM TRANSACT_TABLE WHERE TRANSAC_ID=@TRANSAC_ID
 END

 EXEC TRANSAC 'T1'